# Generated by Django 4.1.5 on 2023-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_app', '0002_alter_device_assigned_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='condition_at_return',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
    ]
